services:
  db:
    image: mysql:5.7
    container_name: taskhive_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: taskhive
      MYSQL_USER: taskhive_user
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - taskhive_network

  php:
    image: php:7.4-fpm
    container_name: taskhive_php
    volumes:
      - ./app:/var/www/html/app
      - ./public:/var/www/html/public
    depends_on:
      - db
    networks:
      - taskhive_network
    build:
      context: .
      dockerfile: Dockerfile

  web:
    image: nginx:latest
    container_name: taskhive_web
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html/app
      - ./public:/var/www/html/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - taskhive_network

volumes:
  db_data:

networks:
  taskhive_network:
    driver: bridge